### ISSUE TITLE
Not reproducible.

### ISSUE THREAD

**Issue by cheungdaven** [prometheusXN/MR-GNN#1]
Cannot reproduce the reported performance with the given code.

**Comment by prometheusXN** [comment]
Did you preprocess the data as we reported? Deepchem's analysis of some SMILEs strings in original data turned out to be empty, which was a big noise for the model. 
If you have preprocessed the data, shuffling the dataset evenly may help you.

**Comment by cheungdaven** [comment]
I ran on the C900 dataset and get an AUC:0.908 after over 200 runs.

**Comment by prometheusXN** [comment]
I have replied to you by email. I hope our reply will be helpful to you

**Comment by prometheusXN** [comment]
I have replied to you by email. I hope our reply will be helpful to you

**Comment by prometheusXN** [comment]
I have just run the code, the result is shown in the following.
The AUC is the second metric result, take the following example:
[cid:_Foxmail.1@2dc32887-d30b-d3fc-b852-52dfedfb738e]
Here we only train 5 epochs, but the AUC have already been over 93%.
So, whether you admit the wrong indicator? I think the accuracy of 90.8% is reasonable, but the AUC should not only be 90.8%
________________________________
xunuo0109@hotmail.com

**Comment by prometheusXN** [comment]
I have sent you the email address of gmail.com, please check it~

**Comment by cheungdaven** [comment]
I realized I should run https://github.com/prometheusXN/MR-GNN/blob/master/MR-GNN/para_test9_coLSTM.py to get the performance instead of the one named MRGNN...

Btw, do you have the code of DeepCCI, if so could share it to me? Thank you so much. 

You can close this issue. Sorry for bothering.
