### ISSUE TITLE
pakeage question

### ISSUE THREAD

**Issue by Zeng-B-B** [prometheusXN/MR-GNN#2]
Hello, I encountered issues while trying to set up the virtual environment for your code. 1) I couldn't find the package "deepchem-gpu"; it seems that only "deepchem" is available. So, I attempted to install "deepchem" directly, but I couldn't locate version 2.3.0. When I tried to install it with conda install deepchem==2.3.0, the installation failed. As a result, I tried to download the offline package for deepchem 2.3.0, but I couldn't find it. I only found "deepchem-nightly 2.3.0." Can you confirm if you used deepchem 2.3.0? 2) TensorFlow 1.13.1 is the CPU version. Does that mean you didn't run the code on a GPU? Shouldn't it be TensorFlow-GPU 1.13.1?

**Comment by 11140321** [comment]
您好 我想请问你的这个代码跑通了吗？我在安装包的时候出现一些问题想向您请教一下
